package com.uestc.domain;

public class TbDouban1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.id
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.name
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.director
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.language
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.duration
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.type
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.time
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.area
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.url
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban1.status
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.id
     *
     * @return the value of douban1.id
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.id
     *
     * @param id the value for douban1.id
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.name
     *
     * @return the value of douban1.name
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.name
     *
     * @param name the value for douban1.name
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.director
     *
     * @return the value of douban1.director
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.director
     *
     * @param director the value for douban1.director
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.language
     *
     * @return the value of douban1.language
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.language
     *
     * @param language the value for douban1.language
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.duration
     *
     * @return the value of douban1.duration
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.duration
     *
     * @param duration the value for douban1.duration
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.type
     *
     * @return the value of douban1.type
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.type
     *
     * @param type the value for douban1.type
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.time
     *
     * @return the value of douban1.time
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.time
     *
     * @param time the value for douban1.time
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.area
     *
     * @return the value of douban1.area
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.area
     *
     * @param area the value for douban1.area
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.url
     *
     * @return the value of douban1.url
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.url
     *
     * @param url the value for douban1.url
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban1.status
     *
     * @return the value of douban1.status
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban1.status
     *
     * @param status the value for douban1.status
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}