package com.uestc.domain;

public class TbDouban2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban2.id
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban2.commentnumber
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    private String commentnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban2.score
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column douban2.date
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban2.id
     *
     * @return the value of douban2.id
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban2.id
     *
     * @param id the value for douban2.id
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban2.commentnumber
     *
     * @return the value of douban2.commentnumber
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    public String getCommentnumber() {
        return commentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban2.commentnumber
     *
     * @param commentnumber the value for douban2.commentnumber
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    public void setCommentnumber(String commentnumber) {
        this.commentnumber = commentnumber == null ? null : commentnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban2.score
     *
     * @return the value of douban2.score
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban2.score
     *
     * @param score the value for douban2.score
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column douban2.date
     *
     * @return the value of douban2.date
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column douban2.date
     *
     * @param date the value for douban2.date
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}