package com.uestc.domain;

import lombok.Data;

@Data
public class TbStartUrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column starturl.id
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column starturl.name
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column starturl.url
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column starturl.id
     *
     * @return the value of starturl.id
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column starturl.id
     *
     * @param id the value for starturl.id
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column starturl.name
     *
     * @return the value of starturl.name
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column starturl.name
     *
     * @param name the value for starturl.name
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column starturl.url
     *
     * @return the value of starturl.url
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column starturl.url
     *
     * @param url the value for starturl.url
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}