package com.uestc.domain;

public class TbZongheng2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng2.id
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng2.fid
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng2.recommend
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    private String recommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng2.click
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    private String click;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng2.date
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng2.status
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng2.id
     *
     * @return the value of zongheng2.id
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng2.id
     *
     * @param id the value for zongheng2.id
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng2.fid
     *
     * @return the value of zongheng2.fid
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng2.fid
     *
     * @param fid the value for zongheng2.fid
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng2.recommend
     *
     * @return the value of zongheng2.recommend
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng2.recommend
     *
     * @param recommend the value for zongheng2.recommend
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend == null ? null : recommend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng2.click
     *
     * @return the value of zongheng2.click
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public String getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng2.click
     *
     * @param click the value for zongheng2.click
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public void setClick(String click) {
        this.click = click == null ? null : click.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng2.date
     *
     * @return the value of zongheng2.date
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng2.date
     *
     * @param date the value for zongheng2.date
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng2.status
     *
     * @return the value of zongheng2.status
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng2.status
     *
     * @param status the value for zongheng2.status
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}