package com.uestc.domain;

public class TbZongheng1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng1.id
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng1.name
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng1.number
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng1.url
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng1.type
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zongheng1.status
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng1.id
     *
     * @return the value of zongheng1.id
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng1.id
     *
     * @param id the value for zongheng1.id
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng1.name
     *
     * @return the value of zongheng1.name
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng1.name
     *
     * @param name the value for zongheng1.name
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng1.number
     *
     * @return the value of zongheng1.number
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng1.number
     *
     * @param number the value for zongheng1.number
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng1.url
     *
     * @return the value of zongheng1.url
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng1.url
     *
     * @param url the value for zongheng1.url
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng1.type
     *
     * @return the value of zongheng1.type
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng1.type
     *
     * @param type the value for zongheng1.type
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zongheng1.status
     *
     * @return the value of zongheng1.status
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zongheng1.status
     *
     * @param status the value for zongheng1.status
     *
     * @mbg.generated Wed Jun 05 13:45:01 GMT+08:00 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}