package com.uestc.dao;

import com.uestc.domain.TbDouban2;
import com.uestc.domain.TbDouban2Example;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TbDouban2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table douban2
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    long countByExample(TbDouban2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table douban2
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    int deleteByExample(TbDouban2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table douban2
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    int insert(TbDouban2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table douban2
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    int insertSelective(TbDouban2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table douban2
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    List<TbDouban2> selectByExample(TbDouban2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table douban2
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TbDouban2 record, @Param("example") TbDouban2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table douban2
     *
     * @mbg.generated Wed Jun 05 14:40:58 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TbDouban2 record, @Param("example") TbDouban2Example example);
}