package com.uestc.dao;

import com.uestc.domain.TbStartUrl;
import com.uestc.domain.TbStartUrlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TbStartUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    long countByExample(TbStartUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    int deleteByExample(TbStartUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    int insert(TbStartUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    int insertSelective(TbStartUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    List<TbStartUrl> selectByExample(TbStartUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    TbStartUrl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TbStartUrl record, @Param("example") TbStartUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TbStartUrl record, @Param("example") TbStartUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TbStartUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starturl
     *
     * @mbg.generated Mon Jun 03 17:23:37 GMT+08:00 2019
     */
    int updateByPrimaryKey(TbStartUrl record);
}