package com.uestc.dao;

import com.uestc.domain.TbZongheng2;
import com.uestc.domain.TbZongheng2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbZongheng2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zongheng2
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    long countByExample(TbZongheng2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zongheng2
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    int deleteByExample(TbZongheng2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zongheng2
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    int insert(TbZongheng2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zongheng2
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    int insertSelective(TbZongheng2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zongheng2
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    List<TbZongheng2> selectByExample(TbZongheng2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zongheng2
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TbZongheng2 record, @Param("example") TbZongheng2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zongheng2
     *
     * @mbg.generated Sun Jun 02 10:18:12 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TbZongheng2 record, @Param("example") TbZongheng2Example example);
}